-- LivePro — esquema Postgres (Supabase).
-- Espejo fiel del esquema MySQL de producción: mismas tablas, columnas y tipos
-- equivalentes. Nada de v2 acá — así la migración de datos es 1:1 y se puede verificar
-- contra el origen. Los cambios de transmisión propia van en 002.
--
-- Decisiones de traducción:
--   INT UNSIGNED AUTO_INCREMENT  ->  integer GENERATED BY DEFAULT AS IDENTITY
--                                    ("BY DEFAULT" permite insertar los id originales)
--   TINYINT(1)                   ->  smallint  (no boolean: el PHP compara contra 0/1)
--   DATETIME                     ->  timestamptz
--   ON UPDATE CURRENT_TIMESTAMP  ->  trigger (Postgres no lo tiene nativo)

CREATE TABLE IF NOT EXISTS users (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(180) NOT NULL,
    email         varchar(190) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stores (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer      NULL REFERENCES users(id) ON DELETE SET NULL,
    slug         varchar(190) NULL UNIQUE,
    name         varchar(190) NULL,
    site_url     varchar(255) NOT NULL,
    api_key      varchar(255) NOT NULL UNIQUE,
    api_secret   varchar(255) NOT NULL,
    order_status varchar(20)  NOT NULL DEFAULT 'pending',
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_stores_user_id ON stores (user_id);

CREATE TABLE IF NOT EXISTS live_sessions (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id            integer      NOT NULL UNIQUE REFERENCES stores(id) ON DELETE CASCADE,
    youtube_url         text         NULL,
    youtube_video_id    varchar(100) NULL,
    is_live             smallint     NOT NULL DEFAULT 0,
    public_session_key  varchar(80)  NULL,
    session_revision    integer      NOT NULL DEFAULT 0,
    active_product_id   integer      NULL,
    active_variation_id integer      NULL,
    active_product_name varchar(255) NULL,
    active_price        varchar(100) NULL,
    active_image        text         NULL,
    updated_at          timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS live_emission_queue (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       integer      NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    product_id     integer      NOT NULL,
    variation_id   integer      NULL,
    session_key    varchar(80)  NULL,
    event_revision integer      NOT NULL DEFAULT 0,
    product_name   varchar(255) NOT NULL,
    price          varchar(100) NULL,
    image_url      text         NULL,
    created_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_queue_store ON live_emission_queue (store_id, id);

CREATE TABLE IF NOT EXISTS inventory_items (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     integer      NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    product_id   integer      NOT NULL,
    variation_id integer      NULL,
    sku          varchar(190) NULL,
    product_name varchar(255) NOT NULL,
    parent_name  varchar(255) NULL,
    sync_token   varchar(80)  NULL,
    price        varchar(100) NULL,
    stock        varchar(50)  NULL,
    image_url    text         NULL,
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (store_id, product_id, variation_id)
);
CREATE INDEX IF NOT EXISTS idx_inventory_store ON inventory_items (store_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS sync_jobs (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id           integer     NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    status             varchar(30) NOT NULL,
    job_type           varchar(30) NOT NULL DEFAULT 'sync_full',
    sync_token         varchar(80) NOT NULL,
    current_page       integer     NOT NULL DEFAULT 1,
    inserted_count     integer     NOT NULL DEFAULT 0,
    processed_products integer     NOT NULL DEFAULT 0,
    total_products     integer     NOT NULL DEFAULT 0,
    total_pages        integer     NOT NULL DEFAULT 0,
    message            text        NULL,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sync_jobs_store ON sync_jobs (store_id, id DESC);

CREATE TABLE IF NOT EXISTS intent_orders (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id          integer      NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    live_session_id   integer      NULL REFERENCES live_sessions(id) ON DELETE SET NULL,
    widget_session_id varchar(120) NOT NULL,
    customer_name     varchar(190) NOT NULL,
    phone             varchar(60)  NOT NULL,
    email             varchar(190) NULL,
    city              varchar(120) NULL,
    notes             text         NULL,
    product_id        integer      NOT NULL,
    variation_id      integer      NULL,
    qty               integer      NOT NULL DEFAULT 1,
    status            varchar(30)  NOT NULL,
    woo_order_id      integer      NULL,
    error_message     text         NULL,
    created_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_intent_store ON intent_orders (store_id, id DESC);

-- MySQL refrescaba updated_at solo (ON UPDATE CURRENT_TIMESTAMP). Sin esto, el
-- "ORDER BY updated_at DESC" del inventario y de la consola deja de ordenar.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['stores','live_sessions','inventory_items','sync_jobs'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_touch ON %I', t, t);
        EXECUTE format(
            'CREATE TRIGGER trg_%s_touch BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION touch_updated_at()', t, t);
    END LOOP;
END $$;
